image: ghcr.io/cirruslabs/android-sdk:34

stages:
  - test
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle
  - chmod +x ./gradlew
  - echo "sdk.dir=$ANDROID_HOME" > local.properties

test:
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    reports:
      junit: app/build/test-results//*.xml
  except:
    - tags

build:
  stage: build
  script:
    - ./gradlew clean assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk//*.apk
    expire_in: 1 week
  only:
    - master
    - tags