image: ubuntu:22.04

variables:
  ANDROID_HOME: "/usr/local/android-sdk"
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  CI: "true"

stages:
  - setup
  - test
  - build

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - $ANDROID_HOME

setup:
  stage: setup
  script:
    - apt-get update -y
    - apt-get install -y wget unzip openjdk-17-jdk lib32z1
    - update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    - mkdir -p $ANDROID_HOME ~/.android
    - touch ~/.android/repositories.cfg
    - wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/tools.zip
    - unzip -q /tmp/tools.zip -d $ANDROID_HOME
    - mv $ANDROID_HOME/cmdline-tools $ANDROID_HOME/cmdline-tools-latest
    - echo y | $ANDROID_HOME/cmdline-tools-latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-34" "build-tools;34.0.0" "emulator" "system-images;android-34;google_apis;x86_64"
    - chmod +x ./gradlew
    - echo "JAVA_HOME=$JAVA_HOME" >> /etc/environment
    - source /etc/environment

test:
  stage: test
  needs: ["setup"]
  script:
    - export JAVA_HOME=$JAVA_HOME
    - ./gradlew test --no-daemon --stacktrace

build:
  stage: build
  needs: ["setup"]
  script:
    - export JAVA_HOME=$JAVA_HOME
    - ./gradlew assembleDebug --stacktrace --no-daemon
  artifacts:
    paths:
      - app/build/outputs/apk/debug/
    expire_in: 7 days