image: ghcr.io/cirruslabs/android-sdk:34

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  ANDROID_HOME: "/opt/android-sdk-linux"
  CI: "true"

stages:
  - test
  - build

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle
  - chmod +x ./gradlew
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - apt-get update -y
  - apt-get install -y lib32z1 lib32stdc++6

test:
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    when: always
    paths:
      - app/build/reports/tests/
    reports:
      junit:
        - app/build/test-results/test/*.xml
        - app/build/test-results/testDebugUnitTest/*.xml
  except:
    - tags

build:
  stage: build
  script:
    - ./gradlew clean assembleRelease
    - mkdir -p artifacts
    - cp app/build/outputs/apk/release/*.apk artifacts/
  artifacts:
    paths:
      - artifacts/*.apk
    expire_in: 1 week
  only:
    - main
    - master
    - tags