image: openjdk:17-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - test
  - build

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=$CI_PROJECT_DIR/.gradle
  - chmod +x ./gradlew
  - echo "sdk.dir=$ANDROID_HOME" > local.properties

test:
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    paths:
      - app/build/reports/tests/
  only:
    - merge_requests
    - main
  tags:
    - android

build:
  stage: build
  script:
    - ./gradlew clean assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk
  only:
    - main
  tags:
    - android