image: ubuntu:22.04

variables:
  ANDROID_HOME: "/usr/local/android-sdk"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  CI: "true"

stages:
  - setup
  - test
  - build

setup:
  stage: setup
  script:
    - apt-get update -y
    - apt-get install -y wget unzip openjdk-17-jdk lib32z1
    - mkdir -p $ANDROID_HOME ~/.android
    - touch ~/.android/repositories.cfg
    - wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/tools.zip
    - unzip -q /tmp/tools.zip -d $ANDROID_HOME
    - mv $ANDROID_HOME/cmdline-tools $ANDROID_HOME/cmdline-tools-latest
    - echo y | $ANDROID_HOME/cmdline-tools-latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"
    - chmod +x ./gradlew

test:
  stage: test
  needs: ["setup"]
  script:
    - chmod +x ./gradlew
    - ./gradlew test --no-daemon

build:
  stage: build
  needs: ["setup"]
  script:
    - chmod +x ./gradlew
    - ./gradlew assembleDebug --stacktrace --no-daemon
  artifacts:
    paths:
      - app/build/outputs/apk/debug/
    expire_in: 7 days